config/routes.rb
Dojoonde::Application.routes.draw do
  root to: "home#index"
  get "login"  => "sessions#new", :as => :login
  get "logout" => "sessions#destroy", :as => :logout
  get "/auth/:provider/callback" => "sessions#social"
  get "/auth/failure" => "sessions#failure"
  resource :sessions

  get "signup" => "users#new", :as => :signup
  get "users/password" => "users#password", :as => :password
  put "users/change_password" => "users#change_password", :as => :change_password
  resources :users

  resources :dojos do
    get "aconteceram" => :happened, as: :happened, on: :collection

    member do
      put "participar" => :participate, as: :participate
      put "desistir"   => :quit,        as: :quit
      get "copiado"    => :copied,      as: :copied
    end

    resources :retrospectives, except: [:index]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)

  has_many :dojos, dependent: :destroy
  has_many :authentications, dependent: :destroy

  validates_presence_of :name
  validates :email, presence: true, uniqueness: true,
    format: { with: /\A[^@]+@[^@]+\z/ }

  validates :password, length: { minimum: 6 }, :on => :create
  validates_confirmation_of :password, if: ->(u) { u.password.present? }
  validates_presence_of     :password_confirmation, if: ->(u) { u.password.present? }

  def self.login(email, password)
    find_by(email: email).try(:authenticate, password)
  end

  def providers_by_authentications
    authentications.map(&:provider)
  end

  def participate?(dojo)
    present = false
    dojo.participants.each { |participant| present = true if participant.user == self }
    present
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      User.login(@user.email, @user.password)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @user_providers = @user.providers_by_authentications
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path(@user), notice: "Usuário alterado com sucesso."
    else
      render :edit
    end
  end

  def password
    @user = current_user 
  end

  def change_password
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path(@user), notice: "Senha alterada com sucesso!"
    else
      render :password
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def errors_for(attr)
    if attr.any?
      messages = ""
      attr.each {|e| messages << "#{e}<br/>"}
      "<p class='alert alert-error'>#{messages}</p>".html_safe
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-horizontal" } do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <%= f.error_messages %>
    </div>
  <% end %>

  <div class="control-group">
    <%= label_tag(:user_name, "Nome", class: "control-label") %>
    <p class="controls"><%= f.text_field :name, class: "input-xxlarge" %></p>
  </div>

  <div class="control-group">
    <%= label_tag(:user_email, "E-mail", class: "control-label") %>
    <p class="controls"><%= f.text_field :email, class: "input-xxlarge" %></p>
  </div>

  <div class="control-group">
    <%= label_tag(:user_password, "Senha", class: "control-label") %>
    <p class="controls"><%= f.password_field :password, class: "input-xlarge" %></p>
  </div>

  <div class="control-group">
    <%= label_tag(:user_password_confirmation, "Confirmação de Senha", class: "control-label") %>
    <p class="controls"><%= f.password_field :password_confirmation, class: "input-xlarge" %></p>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar', class: "btn btn-primary btn-large" %>
    <%= link_to 'Cancelar', root_path, class: "btn btn-inverse btn-large" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="span4">
    <h2><%= t('users.edit.data') %></h2>

    <%= form_for @user do |f| %>
      <%= f.label :name, class: "control-label" %>
      <p class="controls"><%= f.text_field :name %></p>
      <%= errors_for @user.errors[:name] %>

      <%= f.label :email, class: "control-label" %>
      <p class="controls"><%= f.text_field :email %></p>
      <%= errors_for @user.errors[:email] %>

      <p class="controls">
      <%= link_to t('users.edit.change_password'), password_path, class: "label" %>
      </p>

      <%= f.submit t('general.buttons.save'), class: "btn btn-primary btn-large" %>
      <%= link_to t('general.buttons.cancel'), root_path, class: "btn btn-inverse btn-large" %>
    <% end %>
  </div>

  <div class="span5">
    <h2><%= t('users.edit.profiles') %></h2>

    <ul id="providers" class="nav nav-tabs nav-stacked">
      <li id="twitter">
        <%= render "social/connect", user_providers: @user_providers, provider: "twitter" %>
      </li>
      <li id="github">
        <%= render "social/connect", user_providers: @user_providers, provider: "github" %>
      </li>
      <li id="facebook">
        <%= render "social/connect", user_providers: @user_providers, provider: "facebook" %>
      </li>
    </ul>
  </div>

</div>

<div class="row">
  <div class="span10">
    <h2><%= t('users.edit.dojos') %></h2>

    <% if @user.dojos.any? %>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th><%= Dojo.human_attribute_name(:day) %></th>
            <th><%= Dojo.human_attribute_name(:local) %></th>
            <th><%= Dojo.human_attribute_name(:private) %></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @user.dojos.each do |dojo| %>
            <tr>
              <td><%= l dojo.day %></td>
              <td><%= dojo.local %></td>
              <td><%= t("dojos.private_#{dojo.private?}") %></td>
              <td>
                <%= link_to t('general.buttons.show'), dojo_path(dojo), class:"label label-info" %>
                <%= link_to t('general.buttons.edit'), edit_dojo_path(dojo), class:"label" %>
                <%= link_to t('general.buttons.delete'), dojo_path(dojo), method: :delete,
                      data: { confirm: t('general.confirmations.delete') }, 
                      class: "label label-important" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% else %>
      <p class="well"><%= t('users.edit.without_dojos') %></p>
    <% end %>

    <%= link_to t('users.edit.new_dojo'), new_dojo_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Registrar-se</h2>
<%= render "form" %>

app/views/users/password.html.erb
<h2>Trocar senha</h2>

<%= form_for(@user, method: :put, url: { action: "change_password" }, html: { class: "form-horizontal" } ) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <%= f.error_messages %>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :password, class: "control-label" %>
    <p class="controls"><%= f.password_field :password, class: "input-xlarge" %></p>
  </div>

  <div class="control-group">
    <%= f.label :password_confirmation, class: "control-label" %>
    <p class="controls"><%= f.password_field :password_confirmation, class: "input-xlarge" %></p>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar', class: "btn btn-primary btn-large" %>
    <%= link_to 'Cancelar', root_path, class: "btn btn-inverse btn-large" %>
  </div>
<% end %>