config/routes.rb
Dojoonde::Application.routes.draw do
  root to: "home#index"
  get "login"  => "sessions#new", :as => :login
  get "logout" => "sessions#destroy", :as => :logout
  get "/auth/:provider/callback" => "sessions#social"
  get "/auth/failure" => "sessions#failure"
  resource :sessions

  get "signup" => "users#new", :as => :signup
  get "users/password" => "users#password", :as => :password
  put "users/change_password" => "users#change_password", :as => :change_password
  resources :users

  resources :dojos do
    get "aconteceram" => :happened, as: :happened, on: :collection

    member do
      put "participar" => :participate, as: :participate
      put "desistir"   => :quit,        as: :quit
      get "copiado"    => :copied,      as: :copied
    end

    resources :retrospectives, except: [:index]
  end
end

app/models/dojo.rb
class Dojo < ActiveRecord::Base
  belongs_to :user
  has_one :retrospective, dependent: :delete
  has_many :participants

  validates_presence_of :day, :local, :gmaps_link, :user
  validate :day_cannot_be_in_the_past, on: :create

  scope :happened,      -> { where("day <  ? ", Date.today).order("day DESC") }
  scope :not_happened,  -> { where("day >= ? ", Date.today).order("day ASC")  }
  scope :publishable,   -> { where(private: false) }

  before_create :add_creator_of_the_dojo_as_a_participant

  def to_s
    I18n.t("dojos.to_s.private_#{self.private?}", day_formatted: I18n.l(day), local: local)
  end

  def include_participant!(participant)
    self.participants.create(user_id: participant.id)
  end

  def remove_participant!(participant)
    self.participants.each { |p| p.destroy if p.user == participant }
  end

  private
  def day_cannot_be_in_the_past
    errors.add(:day, :cannot_be_in_the_past) if day.present? && day < Date.today
  end

  def add_creator_of_the_dojo_as_a_participant
    unless self.user.participate?(self)
      self.participants.build(user_id: user.id) 
    end
  end
end

app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  before_filter :require_login, only: [:new, :create, :edit, :update,
                                       :destroy, :participate]
  before_action :set_dojo, only: [:edit, :show, :update, :participate, 
                                  :quit, :copied, :destroy]

  def new
    @dojo = Dojo.new
  end

  def create
    @dojo = Dojo.new(dojo_params)
    @dojo.user = current_user

    if @dojo.save
      redirect_to @dojo, notice: 'Dojo cadastrado com sucesso.'
    else
      render :new
    end
  end

  def copied
    @dojo = Dojo.new(local: @dojo.local, 
                     info: @dojo.info, 
                     gmaps_link: @dojo.gmaps_link)
    render :new
  end

  def show; end

  def index
    @dojos = Dojo.not_happened.publishable
  end

  def happened
    @dojos = Dojo.happened
  end

  def edit; end

  def update
    if @dojo.update(dojo_params)
      redirect_to @dojo, notice: 'Dojo alterado com sucesso.'
    else 
      render :edit
    end
  end

  def participate
    @dojo.include_participant!(current_user)
    redirect_to @dojo, notice: "Incluído na lista de participantes ;)"
  end

  def quit
    @dojo.remove_participant!(current_user)
    redirect_to @dojo, notice: "Que pena que desistiu :("
  end

  def destroy
    @dojo.destroy
    redirect_to :back, notice: "Dojo excluído com sucesso."
  end

  private
  def dojo_params
    params.require(:dojo).permit(:day, :local, :gmaps_link, :info, :private)
  end

  def set_dojo
    @dojo = Dojo.includes(:user).find(params[:id])
  end
end

app/helpers/dojos_helper.rb
module DojosHelper
  def participate_button(user, dojo = @dojo)
    user && user.participate?(dojo) ?
      link_to(t('helpers.dojos.participate_button.participate_no'), quit_dojo_path(dojo), method: :put, class: "btn btn-danger btn-block") :
      link_to(t('helpers.dojos.participate_button.participate_yes'), participate_dojo_path(dojo), method: :put, class: "btn btn-success btn-block")
  end

  def gravatar_url(user, size=nil)
    if user.try(:email)
      gravatar_id = Digest::MD5.hexdigest(user.email)
      "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    else
      image_url("blank-avatar.jpg")
    end
  end
end

app/views/dojos/_form.html.erb
<%= form_for @dojo, html: { class: "form-horizontal" } do |f| %>
  <% if @dojo.errors.any? %>
    <div class="alert alert-error">
      <%= f.error_messages %>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :day, class: "control-label" %>
    <p class="controls">
      <%= f.text_field :day, value: (l @dojo.day if @dojo.day), class: "input-medium datetime" %>
    </p>
  </div>

  <div class="control-group">
    <%= f.label :local, class: "control-label" %>
    <p class="controls"><%= f.text_field :local, class: "input-xxlarge" %></p>
  </div>

  <div class="control-group">
    <%= f.label :gmaps_link, class: "control-label" %>
    <p class="controls"><%= f.text_field :gmaps_link, class: "input-xxlarge" %></p>
  </div>

  <div class="control-group">
    <%= f.label :info, class: "control-label" %>
    <p class="controls"><%= f.text_area :info, size: "x5", class: "text_area input-xxlarge" %></p>
  </div>

  <div class="control-group">
    <%= f.label :private, class: "control-label" %>
    <p class="controls"><%= f.check_box :private %></p>
  </div>

  <p class="form-actions">
    <%= f.submit t('general.buttons.save'), class: "btn btn-primary btn-large" %>
    <%= link_to t('general.buttons.cancel'), root_path, class: "btn btn-inverse btn-large" %>
  </p>
<% end %>

<%= content_for :javascript do %>
  <%= javascript_include_tag 'jquery.datetime' %>
<% end %>

app/views/dojos/_table.html.erb
<table class="table table-condensed">
  <caption>
    <h2><%= title %></h2>
  </caption>

  <thead>
    <tr>
      <th><%= Dojo.human_attribute_name(:day) %></th>
      <th><%= Dojo.human_attribute_name(:local) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dojos.each do |dojo| %>
      <tr>
        <td><%= l dojo.day %></td>
        <td><%= dojo.local %></td>
        <td><%= link_to t('general.buttons.details'),dojo_path(dojo), class: "badge badge-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dojos/edit.html.erb
<h2>
  <%= t('dojos.edit.title') %> | 
  <%= link_to t('dojos.edit.copy'), copied_dojo_path(@dojo), class: "btn btn-primary" %> |
  <% if @dojo.retrospective && @dojo.retrospective.not_empty? %>
    <%= link_to t('dojos.edit.edit_retrospective'), edit_dojo_retrospective_path(@dojo, @dojo.retrospective), class: "btn btn-success" %>
  <% else %>
    <%= link_to t('dojos.edit.new_retrospective'), new_dojo_retrospective_path(@dojo), class: "btn btn-success" %>
  <% end %>
</h2>

<%= render "form" %>

app/views/dojos/happened.html.erb
<%= render "table", collection: @dojos, title: t('dojos.happened.title') %>
<%= link_to t('general.buttons.back'), root_path, class: "btn btn-large" %>

app/views/dojos/index.html.erb
<%= render "table", collection: @dojos, title: t('dojos.index.title') %>
<%= link_to t('general.buttons.new'), new_dojo_path, class: "btn btn-large btn-primary" %>
<%= link_to t('general.buttons.back'), root_path, class: "btn btn-large" %>

app/views/dojos/new.html.erb
<h2><%= t('dojos.new.title') %></h2>
<%= render "form" %>

app/views/dojos/show.html.erb
<h2><%= @dojo.to_s %></h2>

<div class="row">
  <div class="span3">

    <div id="participants" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><%= Participant.model_name.human(count: 2) %></h3>
      </div>
      <div class="modal-body">
        <p>
        <% @dojo.participants.each do |participant| %>
          <div class="media pull-left avatar-box">
            <%= image_tag gravatar_url(participant.user), title: participant.name, class: 'img-rounded' %></br >
            <%= participant.name %>
          </div>
        <% end %>
        </p>
      </div>
    </div>

    <%= link_to '#participants', class: "btn btn-info btn-block", role: "button", "data-toggle" => "modal" do %>
      <%= t('dojos.show.participants', count: @dojo.participants.size) %>
    <% end %>

    <%= participate_button(current_user) %>
    <br/>

    <% unless @dojo.private? %>
      <strong><%= t('general.buttons.share') %></strong>
      <br/>

      <!-- Facebook -->
      <iframe src="//www.facebook.com/plugins/like.php?href=<%= dojo_url(@dojo) %>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;font&amp;colorscheme=light&amp;action=like&amp;height=21&amp;localte=pt_BR"
        scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:20px;" allowTransparency="true"></iframe>

      <!-- Twitter -->
      <a href="https://twitter.com/share" class="twitter-share-button" data-text="Dojo, onde? <%=@dojo %> -> <%= dojo_url(@dojo) %>" data-via="dojoonde">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <% end %>

    <p>
      <strong><%= t('dojos.show.who_registered') %></strong><br />
      <%= @dojo.user.name %>
    </p>

    <p>
      <strong><%= t('dojos.show.informations') %>:</strong><br />
      <%= @dojo.info.gsub(/\n/,"<br />").html_safe %>
    </p>
  </div>

  <div class="span7">
    <iframe height="350" width="100%" frameborder="0" marginheight="0" marginwidth="0"
            src="<%= @dojo.gmaps_link.html_safe %>&output=embed">
    </iframe>
    <p>
      <a href="<%= @dojo.gmaps_link.html_safe %>" target="_blank">
        <%= t('dojos.show.unavailable_google_map') %>
      </a>
    </p>
  </div>
</div>

<% if @dojo.retrospective && @dojo.retrospective.not_empty? %>
  <%= render partial: "retrospectives/show", locals: { retrospective: @dojo.retrospective } %>
<% end %>

<br/><br/>

<div id="disqus_thread"></div>

<script type="text/javascript">
  var disqus_shortname = 'dojoonde';
  var disqus_url = '<%= dojo_url(@dojo) %>';

  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>

<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

<%= link_to t('general.buttons.back'), dojos_path, class: "btn btn-large" %>

<%= content_for :javascript do %>
  <%= javascript_include_tag 'bootstrap.modal' %>
<% end %>