config/routes.rb
Dojoonde::Application.routes.draw do
  root to: "home#index"
  get "login"  => "sessions#new", :as => :login
  get "logout" => "sessions#destroy", :as => :logout
  get "/auth/:provider/callback" => "sessions#social"
  get "/auth/failure" => "sessions#failure"
  resource :sessions

  get "signup" => "users#new", :as => :signup
  get "users/password" => "users#password", :as => :password
  put "users/change_password" => "users#change_password", :as => :change_password
  resources :users

  resources :dojos do
    get "aconteceram" => :happened, as: :happened, on: :collection

    member do
      put "participar" => :participate, as: :participate
      put "desistir"   => :quit,        as: :quit
      get "copiado"    => :copied,      as: :copied
    end

    resources :retrospectives, except: [:index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><%= t('app.name') %></title>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= yield :stylesheet %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

  <div class="row">
    <div class="span6 pull-left">
      <header>
      <h1>
        <%= link_to t('app.name'), root_path %>
        <a href="http://twitter.com/dojoonde" target="_blank">
          <%= image_tag "twitter.png" %>
        </a>
      </h1>
      </header>
    </div>

    <div id="welcome" class="span3 pull-right">
      <% if current_user %>
        <%= t('app.header.welcome_message_html', username_link: link_to(current_user.name, edit_user_path(current_user))) %>
        <i class="icon-user"></i>
        <br />
        <%= link_to t('app.header.logout'), logout_path %>
      <% else %>
        <%= t('app.header.login_or_signup_html', login_link: link_to(t('app.header.login'), login_path),
                                                 signup_link: link_to(t('app.header.signup'), signup_path)) %>
      <% end %>
    </div>
  </div>

  <div class="navbar">
    <div class="navbar-inner">
      <nav>
        <ul class="nav">
          <li><%= link_to t('app.header.menu.index'), root_path %></li>
          <li><%= link_to t('app.header.menu.new_dojo'), new_dojo_path %></li>
          <li><%= link_to t('app.header.menu.next_dojos'), dojos_path %></li>
          <li><%= link_to t('app.header.menu.happened_dojos'), happened_dojos_path %></li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="row">
    <div class="span10">

      <% if flash[:notice] %>
        <p class="alert alert-info"><%= notice %></p>
      <% elsif flash[:alert] %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </div>

  <div class="row">
    <div class="span10">
      <footer>
        <hr />
        <%= t('app.footer.text_html') %>
      </footer>
    </div>
  </div>

  <%= javascript_include_tag "application" %>
  <%= yield :javascript %>
</body>
</html>